ARG NODE_VERSION=16

FROM node:$NODE_VERSION-buster as builder

WORKDIR /app

COPY package.json yarn.lock
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn bootstrap
RUN rm -rf /app/packages/server/dist/ && yarn build --scope=server


FROM node:$NODE_VERSION-buster-slim as production
WORKDIR /app

COPY --from=builder /app/packages/server/dist/ /app/
COPY --from=builder /app/packages/server/package.json /app/package.json
RUN yarn install --production=true

CMD [ "node", "/app/index.js" ]
